refactor: add log-info/log-warning functions
These functions don't use `echo -e`, instead bash is used to
enter the escape codes using $'C-style' escaping.

diff --git a/ssh-legion b/ssh-legion
--- a/ssh-legion
+++ b/ssh-legion
@@ -2,9 +2,9 @@
 #
 # Creates an SSH Tunnel to the specified server.
 
-reset='\033[0m'       # Text Reset
-cyan='\033[0;36m'     # Cyan
-yellow='\033[33m'     # yellow
+reset=$'\033[0m'       # Text Reset
+cyan=$'\033[0;36m'     # Cyan
+yellow=$'\033[0;33m'   # yellow
 
 # taken from sysexits.h
 # Used as a return code for when ssh-tunnel fails because the port is in use
@@ -19,15 +19,23 @@ function ssh-global-options() {
   fi
 }
 
+function log-info() {
+  echo "${cyan}Info: ${1}${reset}" >&2
+}
+
+function log-warning() {
+  echo "${yellow}Warning: ${1}${reset}" >&2
+}
+
 function ssh-check() {
   local CONNECTION_TIME="1s"
   local RETRY_ON_SUCCESS_EXIT="0"
   # run ssh-legion for 1s only, then exit
 
   if ssh-legion "$CONNECTION_TIME" "$RETRY_ON_SUCCESS_EXIT"; then
-    echo -e "${cyan}Info: Testing SSH tunnel connection to ${destination} succeeded." >&2
+    log-info "Testing SSH tunnel connection to ${destination} succeeded."
   else
-    echo -e "${cyan}Info: Testing SSH tunnel connection to ${destination} failed." >&2
+    log-info "Testing SSH tunnel connection to ${destination} failed."
     return 1
   fi
 }
@@ -46,7 +54,7 @@ function ssh-legion() {
   if [ -f /var/lib/dbus/machine-id ]; then
     MACHINE_ID=$(cat /var/lib/dbus/machine-id)
   else
-    echo -e "${cyan}Info: No dbus machine-id found, creating one from mac addresses.${reset}"
+    log-info 'No dbus machine-id found, creating one from mac addresses.'
     mac="$(cat /sys/class/net/*/address | head -1)"
     MACHINE_ID="$(( 0x"${mac//:/''}" ))"
   fi
@@ -65,7 +73,7 @@ function ssh-legion() {
   SALTED_MACHINE_ID=${SALTED_MACHINE_ID//"+"/"-"}
   MYNAME="$(id -u -n)@$(uname -n)"
 
-  echo -e "${cyan}Info: Creating tunnel to ${destination}, use CTRL+C to cancel.${reset}" >&2
+  log-info "Creating tunnel to ${destination}, use CTRL+C to cancel."
 
   # used on purpose to send FNAME to the remote side
   # shellcheck disable=SC2029
@@ -74,7 +82,7 @@ function ssh-legion() {
     if ! ssh-tunnel "$PORT" "$host_port" "$destination" "$CONNECTION_TIME"; then
       # RemotePortForwarding Failed!
       # Port already in use
-      echo -e "${yellow} Tunneling from port ${PORT} ${destination} failed, retrying with a random port.${reset}" >&2
+      log-warning "Tunneling from port ${PORT} ${destination} failed, retrying with a random port."
       # Try using random ports until one works.
 
       # we want a port between 1024 and 65535, range of 64511 numbers
@@ -203,7 +211,7 @@ function view-key() {
   if [ ! -f ~/.ssh/id_ed25519 ]; then
     ssh-keygen -t ed25519 -N "" -C "$(id -u -n)@$(uname -n)" -f ~/.ssh/id_ed25519
   fi
-  echo -e "${cyan}Info: Ouputing ~/.ssh/id_ed25519.pub, please add to your server's ~/.ssh/authorized_keys file.${reset}" >&2
+  log-info "Ouputing ~/.ssh/id_ed25519.pub, please add to your server's ~/.ssh/authorized_keys file."
   cat ~/.ssh/id_ed25519.pub
 }
 
